### ISSUE TITLE
Format reference to equation?

### ISSUE THREAD

**Issue by tdehaeze** [jethrokuan/org-ref-ox-hugo#1]
Hi @jethrokuan,

I am not sure if this issue should be posted to `org-ref`, `ox-hugo` or here.
Please tell me if this does not belongs here.

Lets say I have the following equation:
```
\begin{equation}
  a = 2 \label{eq:label}
\end{equation}
```

I would like to reference to equations using `eqref:eq:label` (`org-ref` way to do reference to equations).

The thing is that when I export to markdown using `org-hugo-export-to-markdown`, what I obtain is `[eq:label](#eq:label)` which is not what I want (and the link does not work at all).

I would like to have `(1)` that links to the equation as I usually obtain when I export to html.

One solution I could find is to directly use `\eqref{eq:label}` (in org-mode) and let mathjax render the link correctly.

But then inside org-mode, the link does not work and it's not ideal.

Do you think that would be possible to somehow automatically substitute `eqref:eq:label` to `\eqref{eq:label}` when exporting to markdown with hugo?

Thanks a lot

**Comment by kaushalmodi** [comment]
As for `ox-hugo`, see the use of `\label{eq:1}` and `\ref{eq:1}` in https://ox-hugo.scripter.co/doc/equations/#environments.

Related ox-hugo test: https://ox-hugo.scripter.co/test/posts/links-to-equations

**Comment by tdehaeze** [comment]
Whenever I use `\ref{eq:1}` in my org file, it does indeed work.

But I would rather use `eqref:eq:1` that would then be automatically converted to `\ref{eq:1}` in the markdown file when I use `org-hugo-export-to-markdown`.

**Comment by tdehaeze** [comment]
I guess I should modify this line in the `org-ref` package: https://github.com/jkitchin/org-ref/blob/5bb9be2232db72b04754d7e4c02a3976ad422f6f/org-ref-core.el#L1960

I close this issue.
Thanks
